### ISSUE TITLE
Newline at end of url match patterns settings box breaks everything

### ISSUE THREAD

**Issue by jaronheard** [g3rv4/OnChrome#1]
If you have an extra newline or other character in your settings box, it will break everything

## works
<img width="401" alt="image" src="https://user-images.githubusercontent.com/7065695/77863688-eb227500-71d8-11ea-9386-9345b34d0284.png">
but if you hit enter and save, everything will break.

Thanks for this! Figured I'd document this issue in case others ran into trouble.

**Comment by g3rv4** [comment]
sorry that it took me this long to look into this :S I've just fixed it on df900e70f22220f46ec87e67306e0a76746ad328 and submitted version 1.0.1 to the store :)
