### ISSUE TITLE
Excluding URLs does not work

### ISSUE THREAD

**Issue by TobiasWenzel** [g3rv4/OnChrome#10]
I want all Google URLs to be opened in Chrome, except for accounts.google.com. So this is how I configured OnChrome:

![image](https://user-images.githubusercontent.com/10582928/177740047-89fa435d-20b0-4b81-9175-6e859f0b279c.png)

Unfortunately the **exclusion does not work**, it will also open https://accounts.google.com/ in Chrome (as well as all other *.google.com URLs, which is fine).
I already tried experimenting with different schemes. For example, I also tried the appropriate URL match pattern `*://accounts.google.com/*` in the exclusion, although it clearly states that the exclusion URL has to be a regular expression. But that didn't work either.

Any help would be appreciated.

**Comment by g3rv4** [comment]
I think I understand what happens there :)

You go to `accounts.google.com`, and OnChrome does the right thing (it doesn't open Chrome for that). However, then Google redirects you to `myaccount.google.com`. And that doesn't match your exclusions list.

Give it a try with `.*accounts?\.google\.com.*` as the regular expression

**Comment by TobiasWenzel** [comment]
Cool, that worked! 😀
Thank you very much! Nice extension! 👍
